' Merchandising.Infrastructure.Security.CertificateOptions
'
' Binds the ACL-protected host certificate configuration file into strongly
' typed options. The file lives outside the repository and outside the
' binaries, at %ProgramData%\MerchandisingSystem\config\certificate.json on
' the host - see docs/installation-guide.md. The .pfx it points at carries a
' private key and gets exactly the same treatment as the database password
' (CLAUDE.md section 4, guardrail G-C): never committed, never logged, never
' read by anything but the API process.
'
' Deserialized with reflection-based System.Text.Json, matching
' DatabaseOptions - see that type's comment for why no source generator is
' used here.

Imports System.Text.Json.Serialization

Namespace Security

    ''' <summary>
    ''' Kestrel HTTPS certificate settings, bound from the host configuration
    ''' file rather than from any committed source.
    ''' </summary>
    Public NotInheritable Class CertificateOptions

        ''' <summary>
        ''' Full path to the PKCS#12 (.pfx) file containing the certificate
        ''' and its private key. Generated by
        ''' <c>scripts/create-dev-certificate.ps1</c>; never committed.
        ''' </summary>
        <JsonPropertyName("pfxPath")>
        Public Property PfxPath As String = String.Empty

        ''' <summary>Password protecting <see cref="PfxPath"/>. Never logged.</summary>
        <JsonPropertyName("password")>
        Public Property Password As String = String.Empty

    End Class

End Namespace
